# Generated by Django 5.0.3 on 2025-03-28 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='type_operation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='directory.typeoperation'),
            preserve_default=False,
        ),
    ]
