# Generated by Django 5.0.3 on 2025-03-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_alter_dds_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dds',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
