# Generated by Django 5.0.3 on 2025-03-30 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_alter_dds_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='parent',
        ),
        migrations.CreateModel(
            name='Subcategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.subcategories')),
            ],
        ),
        migrations.AlterField(
            model_name='dds',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_dds', to='directory.subcategories'),
        ),
    ]
