# Generated by Django 5.0.3 on 2025-03-30 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_remove_categories_parent_subcategories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategories',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.categories'),
        ),
    ]
